/** Keys of the inline SVG icon set rendered by the shared icon component (no icon fonts). */
export type IconName =
  // Decor & event categories
  | 'flower'
  | 'garland'
  | 'bulb'
  | 'string-lights'
  | 'balloon'
  | 'speaker'
  | 'mic'
  | 'stage'
  | 'backdrop'
  | 'mandap'
  | 'arch'
  | 'chair'
  | 'sofa'
  | 'carpet'
  | 'drum'
  | 'screen'
  | 'sparkler'
  | 'camera'
  | 'truck'
  | 'palette'
  // Event types & general
  | 'wedding'
  | 'ring'
  | 'home'
  | 'lamp'
  | 'cake'
  | 'briefcase'
  | 'tent'
  | 'festival'
  // UI & contact
  | 'phone'
  | 'whatsapp'
  | 'mail'
  | 'pin'
  | 'clock'
  | 'star'
  | 'chevron'
  | 'close'
  | 'menu'
  | 'instagram'
  | 'facebook'
  | 'youtube';
